restaurant_kitchen_service/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.http import request
from django.urls import path, include

from restaurant_kitchen_service import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("service.urls", namespace="service")),
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

service/urls.py
from django.urls import path

from service.views import (
    index,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishListView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishDetailView,
    toggle_assign_to_dish,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookYearOfExperienceUpdateView,
    CookDeleteView,
    IngredientUpdateView,
)


urlpatterns = [
    path("", index, name="index"),
    path(
        "dish_type/",
        DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish_type/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
path(
        "dish_type/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish_type/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish_type-delete",
    ),
    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path(
        "dish/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
    path("cook/", CookListView.as_view(), name="cook-list"),
    path(
        "cook/<int:pk>/", CookDetailView.as_view(), name="cook-detail"
    ),
    path("cook/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cook/<int:pk>/update/",
        CookYearOfExperienceUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cook/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),
    path("ingredient/<int:pk>/update/", IngredientUpdateView.as_view(), name="ingredient-update"),
]

app_name = "service"

service/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name", )


class Cook(AbstractUser):
    years_of_experience = models.PositiveIntegerField(
        default=0
    )

    class Meta:
        ordering = ("years_of_experience", )

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("service:cook-detail", args=[str(self.id)])


class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.CASCADE,
        related_name="dishes"
    )
    ingredients = models.ManyToManyField(
        Ingredient,
        related_name="dishes_with_this_ingredient"
    )
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes",
        blank=True
    )
    class Meta:
        ordering = ("name", )

    def __str__(self):
        return f"{self.name} (price: {self.price} , dish type: {self.dish_type.name})"

service/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from service.models import Dish, Cook, DishType, Ingredient


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )


class IngredientCreationForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = "__all__"


class CookYearOfExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience"]


class DishTypesSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name",
            }
        )
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name",
            }
        )
    )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by username",
            }
        )
    )

service/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from service.forms import DishForm, DishSearchForm, DishTypesSearchForm, CookSearchForm, CookCreationForm, \
    CookYearOfExperienceUpdateForm, IngredientCreationForm
from service.models import DishType, Cook, Dish, Ingredient


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_dishes = Dish.objects.count()
    num_cookers = Cook.objects.count()
    num_dish_types = DishType.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    context = {
        "num_dishes": num_dishes,
        "num_cookers": num_cookers,
        "num_dish_types": num_dish_types,
        "num_visits": num_visits + 1
    }
    return render(request, "service/index.html", context=context)

class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    paginate_by = 5
    template_name = "service/dish_type_list.html"
    context_object_name = "dish_type_list"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypesSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data["name"]
            if name:
                queryset = queryset.filter(name__icontains=name)
        return queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "service/dish_type_form.html"
    success_url = reverse_lazy("service:dish-type-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "service/dish_type_form.html"
    success_url = reverse_lazy("service:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "service/dish_type_confirm_delete.html"
    success_url = reverse_lazy("service:dish-type-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5
    template_name = "service/dish_list.html"
    context_object_name = "dish_list"
    queryset = Dish.objects.select_related("dish_type").order_by("name")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = DishSearchForm(self.request.GET)
        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dish_type")
        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            model_name = form.cleaned_data.get("name")
            if model_name:
                queryset = queryset.filter(name__icontains=model_name)

        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cook"] = Cook.objects.get(id=self.request.user.id)
        return context


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("service:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("service:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("service:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5
    template_name = "service/cook_list.html"
    context_object_name = "cook_list"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data["username"]
            if name:
                queryset = queryset.filter(username__icontains=name)
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.all().prefetch_related("dishes__dish_type")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookYearOfExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookYearOfExperienceUpdateForm
    success_url = reverse_lazy("service:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("")

@login_required
def toggle_assign_to_dish(request, pk):
    cook = get_object_or_404(Cook, id=request.user.id)
    dish = get_object_or_404(Dish, id=pk)

    if cook.dishes.filter(id=dish.id).exists():
        cook.dishes.remove(dish)
    else:
        cook.dishes.add(dish)
    return redirect(reverse_lazy("service:dish-detail", kwargs={"pk": pk}))


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    form_class = IngredientCreationForm
    success_url = reverse_lazy("service:dish-list")
    template_name = "service/ingredient_form.html"

templates/service/cook_confirm_delete.html
{% extends 'layouts/base-presentation.html' %}

{% block content %}
<div class="card p-4 mx-auto mt-7 text-center" style="max-width: 400px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <h2 class="card-title mb-4">Delete cook?</h2>
    <p>Are you sure you want to delete this cook?</p>
    <form action="" method="post">
      {% csrf_token %}
      <div class="d-grid gap-2">
        <input type="submit" value="Yes" class="btn btn-danger mt-3">
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/service/cook_detail.html
{% extends 'layouts/base-presentation.html' %}

{% block content %}
<div class="card p-4 mx-auto mt-7" style="max-width: 800px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h2 class="card-title">Username: {{ cook.username }}</h2>
      <div>
        <a href="{% url 'service:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page me-2">
          Delete
        </a>
        <a href="{% url 'service:cook-update' pk=cook.id %}" class="btn btn-secondary link-to-page">
          Update Year Of Experience
        </a>
      </div>
    </div>

    <hr>

    <p><strong>First name:</strong> {{ cook.first_name }}</p>
    <p><strong>Last name:</strong> {{ cook.last_name }}</p>
    <p><strong>Year Of Experience:</strong> {{ cook.years_of_experience }}</p>

    <hr>

    <div class="mt-4">
      <h4 class="mb-3">Dishes</h4>
      {% for dish in cook.dishes.all %}
        <div class="border-bottom pb-2 mb-2">
          <p class="mb-1"><strong>Name:</strong> {{ dish.name }}</p>
          <p class="mb-1"><strong>Dish Type:</strong> {{ dish.dish_type.name }}</p>
          <p class="text-muted mb-0"><strong>Id:</strong> {{ dish.id }}</p>
        </div>
      {% empty %}
        <p>No dish!</p>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/service/cook_form.html
{% extends 'layouts/base-presentation.html' %}
{% load crispy_forms_filters %}

{% block content %}
<div class="card p-4 mx-auto mt-7" style="max-width: 400px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <h2 class="card-title text-center mb-4">Create cook</h2>

    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <div class="d-grid gap-2">
        <input type="submit" value="Submit" class="btn btn-primary mt-3">
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/service/cook_list.html
{% extends 'layouts/base-presentation.html' %}
{% load crispy_forms_filters %}

{% block content %}
<div class="card p-4 mx-auto mt-7" style="max-width: 1000px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h2 class="card-title mb-0">Cook List</h2>
      <a href="{% url 'service:cook-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </div>

    <hr>

    <div class="d-flex justify-content-between align-items-center mb-4">
      <form method="GET" action="" class="d-flex align-items-center">
        {{ search_form|crispy }}
        <input type="submit"  value="🔎"  class="btn btn-secondary ms-2">
      </form>
    </div>

    {% if cook_list %}
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead class="bg-light">
            <tr>
              <th>ID</th>
              <th>Username</th>
              <th>First name</th>
              <th>Last name</th>
              <th>Year Of Experience</th>
            </tr>
          </thead>
          <tbody>
          {% for cook in cook_list %}
            <tr>
              <td>{{ cook.id }}</td>
              <td><a href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a></td>
              <td>{{ cook.first_name }}</td>
              <td>{{ cook.last_name }}</td>
              <td>{{ cook.years_of_experience }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <p>There are no cooks in the list.</p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/service/dish_confirm_delete.html
{% extends "layouts/base-presentation.html" %}

{% block content %}
<div class="card p-4 mx-auto mt-7 text-center" style="max-width: 400px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <h2 class="card-title mb-4">Delete dish?</h2>
    <p>Are you sure you want to delete this dish?</p>
    <form action="" method="post">
      {% csrf_token %}
      <div class="d-grid gap-2">
        <input type="submit" value="Yes" class="btn btn-danger mt-3">
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/service/dish_detail.html
{% extends "layouts/base-presentation.html" %}

{% block content %}
<div class="card p-4 mx-auto mt-7" style="max-width: 800px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h2 class="card-title">{{ dish.name }}</h2>
      <div>
        <a href="{% url 'service:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page me-2">
          Delete
        </a>
        <a href="{% url 'service:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
          Update
        </a>
      </div>
    </div>

    <hr>

    <p><strong>Dish Type:</strong> {{ dish.dish_type.name }}</p>
    <p><strong>Dish Description:</strong></p>
    <p class="text-muted">{{ dish.description }}</p>

    <hr>

    <div class="mt-4">
      <h4 class="mb-3">Ingredients</h4>
      <ul class="list-group list-group-flush">
        {% for ingredient in dish.ingredients.all %}
          <li class="list-group-item">{{ ingredient.name }}</li>
        {% empty %}
          <li class="list-group-item">No ingredients listed.</li>
        {% endfor %}
      </ul>
    </div>

    <hr>

    <div class="mt-4">
      <h4 class="mb-3">Cooks</h4>
      <div class="mb-3">
        {% if dish in cook.dishes.all %}
          <a href="{% url 'service:toggle-dish-assign' pk=dish.id %}" class="btn btn-danger link-to-page">
            Delete me from this dish
          </a>
        {% else %}
          <a href="{% url 'service:toggle-dish-assign' pk=dish.id %}" class="btn btn-success link-to-page">
            Assign me from this dish
          </a>
        {% endif %}
      </div>

      <ul class="list-group list-group-flush">
        {% for cook in dish.cooks.all %}
          <li class="list-group-item">{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</li>
        {% empty %}
          <li class="list-group-item">No cooks assigned.</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/service/dish_form.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="card p-4 mx-auto mt-7" style="max-width: 600px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <h2 class="card-title text-center mb-4">{{ object|yesno:"Update,Create" }} dish</h2>

    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <div class="d-grid gap-2">
        <input type="submit" value="Submit" class="btn btn-primary mt-3">
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/service/dish_list.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="card p-4 mx-auto mt-7" style="max-width: 800px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h2 class="card-title mb-0">Dish list</h2>
      <a href="{% url 'service:dish-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </div>

    <hr>

    <div class="d-flex justify-content-between align-items-center mb-4">
      <form method="GET" action="" class="d-flex align-items-center">
        {{ search_form|crispy }}
        <input type="submit"  value="🔎"  class="btn btn-secondary ms-2">
      </form>
    </div>

    {% if dish_list %}
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead class="bg-light">
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Type</th>
            </tr>
          </thead>
          <tbody>
          {% for dish in dish_list %}
            <tr>
              <td><a href="{% url 'service:dish-detail' pk=dish.id %}">{{ dish.id }}</a></td>
              <td>{{ dish.name }}</td>
              <td>{{ dish.dish_type.name }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <p>There are no dishes in the list.</p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/service/dish_type_confirm_delete.html
{% extends "layouts/base-presentation.html" %}

{% block content %}
<div class="card p-4 mx-auto mt-7 text-center" style="max-width: 400px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <h2 class="card-title mb-4">Delete Dish Type?</h2>
    <p>Are you sure you want to delete this dish type?</p>
    <form action="" method="post">
      {% csrf_token %}
      <div class="d-grid gap-2">
        <input type="submit" value="Yes" class="btn btn-danger mt-3">
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/service/dish_type_form.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="card p-4 mx-auto mt-7" style="max-width: 400px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <h2 class="card-title text-center mb-4">{{ object|yesno:"Update,Create" }} dish_type</h2>

    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <div class="d-grid gap-2">
        <input type="submit" value="Submit" class="btn btn-primary mt-3">
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/service/dish_type_list.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="card p-4 mx-auto mt-7" style="max-width: 800px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h2 class="card-title mb-0">Dish Type List</h2>
      <a href="{% url 'service:dish-type-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </div>

    <hr>

    <div class="d-flex justify-content-between align-items-center mb-4">
      <form method="GET" action="" class="d-flex align-items-center">
        {{ search_form|crispy }}
        <input type="submit"  value="🔎"  class="btn btn-secondary ms-2">
      </form>
    </div>

    {% if dish_type_list %}
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead class="bg-light">
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Update</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
          {% for dish_type in dish_type_list %}
            <tr>
              <td>
                  {{ dish_type.id }}
              </td>
              <td>
                  {{ dish_type.name }}
              </td>
              <td>
                  <a href="{% url 'service:dish-type-update' pk=dish_type.id %}" class="btn btn-secondary btn-sm">
                    Update
                  </a>
                </td>
                <td>
                  <a href="{% url 'service:dish_type-delete' pk=dish_type.id %}" class="btn btn-danger btn-sm">
                    Delete
                  </a>
                </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <p>There are no dish types in the list.</p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/service/ingredient_form.html
{% extends 'layouts/base-presentation.html' %}
{% load crispy_forms_filters %}

{% block content %}
<div class="card p-4 mx-auto mt-7" style="max-width: 400px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
  <div class="card-body">
    <h2 class="card-title text-center mb-4">{{ object|yesno:"Update,Create" }} ingredient</h2>

    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <div class="d-grid gap-2">
        <input type="submit" value="Submit" class="btn btn-primary mt-3">
      </div>
    </form>
  </div>
</div>
{% endblock %}